[tool.poetry]
name = "clipboard-processor"
version = "0.1.0"
description = ""
authors = ["Thomas Reifenberger <tom-mi@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "clipboard_processor", from = "src"}]

[tool.poetry.scripts]
clipboard-processor = "clipboard_processor.cli:main"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
pyperclip = "^1.9.0"
desktop-notifier = "^5.0.1"
vininfo = "^1.8.0"
python-ulid = "^2.7.0"
pyjwt = {extras = ["crypto"], version = "^2.8.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
