name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
      - name: Install packages
        run: sudo apt-get install xclip xvfb python3-tk
      - uses: actions/checkout@v4
      - name: Install Hatch
        uses: pypa/hatch@a3c83ab3d481fbc2dc91dd0088628817488dd1d5
      - name: Run tests
        run: xvfb-run -a -w 1 hatch test --all
      - name: Run tests for minimal installation
        run: xvfb-run -a -w 1 hatch run test-minimal:run
      - name: Run snapshot tests
        run: hatch run test-snapshot:run # already runs in xvfb
      - name: Build
        run: hatch build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
